const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR05vTUtXM2hnZ2RkRXJHd2wwaHhMZFhXOTNLVmF4UWJabU5Qa1YwUUtVMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVDk1cEhvMUhjVTBselJvS0NvRUNYbDdUd24vaXEraEpQUEQ2Q1VQRVVsVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVSmlVc1pEdWJYY1JzN0RDVkZHVlhCWjY0dlNCNzlFSFlmeFdQQzMyZVZjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvcDFZRmQ1OU14YkhMRjBjZFZvbms2S1NoN284dCt4RWVDK05WRlliUzNZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVLMTc4M3BmeDlZMDZsdXUrS21hemtUcnZ0WjF0ZW8vQ1lzdEFRcnhibWc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImEwUGJpQUswM1dqNXVEcHJZd0NBTVR2aVFDMERaaUNHK0N5T1dFdUR1R2c9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0FjaXNSWFhMUTJNR0N3K0FPWkdURW5xeUEvSXFqdm1HVU1KemFkZnVGaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMVhoM1R2ckRjQk9ZdXpVUTVVMEErc3JCcURZdWJkYmdKNXJlVUlQT09WUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imk5Q3Q3MjNNR0E4UGM4T3FpU1NJamtIRjdPMkFLeldGSXFFZTBvWEMyVWR5Z2dJYnhkeFpZT0FrcnpDUUU1TnhoNWhNbmZJZWc4QWlVL1FweDU4OGdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTI3LCJhZHZTZWNyZXRLZXkiOiJyVzhtaG1kY3VFTVNobVB5QlhXdFJvYlVOMWxHeEZ4YUdsYkpCVXYvek5RPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6ZmFsc2UsImFjY291bnQiOnsiZGV0YWlscyI6IkNQaXhpRVlRM0tXbHp3WVlBaUFBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJiSVp6ZkFJSnBPbXhlOU5jS0xHWEsvdHg3MVhDSnVSL2t1dWxHQnhWeUVJPSIsImFjY291bnRTaWduYXR1cmUiOiJwNkFuVy9zcENJMzdUS2s5RXhZalhLR2RMV1kyaHVRMUN5SEVVTHFMVXNGaVRrVzE0WkQzMVRuL2xRNXBnWmtkb2pHL2lLY1VSdEFnN3NBOTM0ZnFCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiVkZIT2FBczB5Vmd0K0pyMjladzZ6WW8vellkMlphM1AvWmJaNmM4aEJiUDJPWG5LUE9YZ08rdTFQOVhDVmU4VStsaVBrUlRKK0E4bFR4aGJQYkFkanc9PSJ9LCJtZSI6eyJpZCI6IjI1NDc5ODQ5MDg0NDo1NUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjU1MTY0NjI3MTIwMjIyOjU1QGxpZCJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3OTg0OTA4NDQ6NTVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV3lHYzN3Q0NhVHBzWHZUWENpeGx5djdjZTlWd2lia2Y1THJwUmdjVmNoQyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSURRZ1MifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzc2ODk4NzkxfQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "private",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "254798490844",
  "OWNER_NAME": process.env.OWNER_NAME || "Barrown",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'false',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'false',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'false',
  "AUTO_REACT": process.env.AUTO_REACT === 'false',
  "WELCOME": process.env.WELCOME === 'false',
  "ANTI_BAD": process.env.ANTI_BAD === 'false',
  "ANTI_LINK": process.env.ANTI_LINK === 'false',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'false',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'false',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "💙",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'false'
};
