const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0tuV2tQQjVvUzRYTXJKb3ZJWW1YSkhwWXB1dFAzL25JVW9lMzRLRWwydz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidElhRi9QUFQ3WkxHSEFSdlZKMlFWcDZFanRHV2VrWmIyYlpQRHJYZUgxVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHRjFHR2ZQR2ZCdUNzTnNQYVZNeXc0Z1Y0NkxqVWVuQnQrMFp3cG5PR1ZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3NUxlcmpGWHNGWC9hd1dqdTdxSlh1OFJUYlgxL2FEOTZPamVBSnBhTzNJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJINHpkTjdsVmlTUkNrVVh6ZUVtVmRpV04ybkNGb3E3dndzVlRRSUFwV0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkUwVWo3SE1wdERWWDlWT05ROTRWNjlkazdpbHl1K2xFQnpobk8rNUhKZzA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUhZSm5BcGRpU0RqVktQNUJRZ3JxOHFLSGJHVG9sQ1hBSElkbHlWTXlFbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTlg5b2NLNGxPV3JyWklwdWpZdTlCZmZPMjVyMEE4ZGoyeUtldHJLbjlGZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikhrc1hCTEJBdHFGc2Y4Y1F6Ylp2U2JKWkNVN25iYnE4cHJ3dUtyV3l2a281Q21VQVYvdG12R29rK0E5NmdqaldUWlZLem5oQURocHAxTjFNVnFZQ0RBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTg0LCJhZHZTZWNyZXRLZXkiOiIvYVRPMkhmditSUHBjMG5WS1ZSYmMyR2lpN0pwOEw1N3NxZDZyclBmdFVnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJYUDNOWThBRSIsIm1lIjp7ImlkIjoiMjU0Nzk4NDkwODQ0OjY0QHMud2hhdHNhcHAubmV0IiwibGlkIjoiNTUxNjQ2MjcxMjAyMjI6NjRAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJR3lpRVlRcXFtcXp3WVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJiSVp6ZkFJSnBPbXhlOU5jS0xHWEsvdHg3MVhDSnVSL2t1dWxHQnhWeUVJPSIsImFjY291bnRTaWduYXR1cmUiOiI3UkNMd1J3Qnk1Q1ZtQnh0TnI5aEtOelBxdHh4a1JnZGwwTkJvZHp2c25pSUM5MDlMVzVGZWkwa0x3WkJnM2J0aVorSEhWUElQelRBdDQ3ZUhIU1lCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWkM5NGFWY3JXTnVvSk13aFo5M3Jxa3I2VU1kQVY3NTFhWS83V1F0WGViODJpRXZGalZUR0phc0EzRGJvS0t2a2ZCRXZ4ZmY1SGUrYktZZ29JRys0Qnc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3OTg0OTA4NDQ6NjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV3lHYzN3Q0NhVHBzWHZUWENpeGx5djdjZTlWd2lia2Y1THJwUmdjVmNoQyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSURRZ1MifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzc2OTgxMTcyLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUpxWiJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "private",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "254798490844",
  "OWNER_NAME": process.env.OWNER_NAME || "Barrown",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'false',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'false',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'false',
  "AUTO_REACT": process.env.AUTO_REACT === 'false',
  "WELCOME": process.env.WELCOME === 'false',
  "ANTI_BAD": process.env.ANTI_BAD === 'false',
  "ANTI_LINK": process.env.ANTI_LINK === 'false',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'false',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'false',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "💙",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'false'
};
